version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:4.0-management
    container_name: rabbitmq-picpay
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASS}
    networks:
      - PicPaySimplifiedNW

  api:
    image: ${ACR_LOGIN_SERVER}/picpay-api:${IMAGE_TAG}
    container_name: picpay-api
    ports:
      - "8080:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: ${ASPNETCORE_ENVIRONMENT}
      ConnectionStrings__DefaultConnection: ${MYSQL_CONNECTION_STRING}
      APPLICATIONINSIGHTS_CONNECTION_STRING: ${APPINSIGHTS_CONNECTION_STRING}
      RabbitMQ__Hostname: rabbitmq
      RabbitMQ__Port: 5672
      RabbitMQ__Username: ${RABBITMQ_PASS}
      RabbitMQ__Password: ${RABBITMQ_USER}
      RabbitMQ__Exchange: ${EXCHANGE_NAME}
      RabbitMQ__TransferReceivedQueue: ${RABBITMQ_TRANSFER_RECEIVED_QUEUE}
    depends_on:
      - rabbitmq
    networks:
      - PicPaySimplifiedNW

networks:
  PicPaySimplifiedNW:
    external: true
