version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:4.0-management
    container_name: rabbitmq-picpay
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: gui
      RABBITMQ_DEFAULT_PASS: 123
    networks:
      - PicPaySimplifiedNW

  api:
    build:
      context: .
      dockerfile: ./src/presentation/PipcPaySimplified.Api/Dockerfile
    container_name: picpay-api
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      ASPNETCORE_URLS: http://+:8080
      RabbitMQ__Hostname: rabbitmq
      RabbitMQ__Port: 5672
      RabbitMQ__Username: gui
      RabbitMQ__Password: 123
      RabbitMQ__Exchange: transfer.events
      RabbitMQ__TransferReceivedQueue: transfer.received.queue
    depends_on:
      - rabbitmq
    networks:
      - PicPaySimplifiedNW

networks:
  PicPaySimplifiedNW:
    external: true
